---
title: 'Intervalo_bootstraping'
author: "GonzaloArevalo, Ivan Misle"
date: "2024-08-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library ( boot )
library ( bootES )

# Crear muestra inicial , mostrar su histograma y calcul ar la media .
muestra <- c (79 , 75 , 84 , 75 , 94 , 82 , 76 , 90 , 79 , 88)
datos <- data.frame(muestra)
# Establecer cantidad de remuestreos y nivel de signifi caci ó n .
B = 2000
alfa <- 0.01

cat ( " Paquete boot \ n " )

# Construir distribuci ó n bootstrap usando el paquete boot .
media <- function ( valores , i ) {
mean( valores [ i ])
}
set.seed (432)
distribucion_b <- boot ( muestra , statistic = media , R = B )
print ( distribucion_b )

# Graficar distribuci ó n bootstrap .
print ( plot ( distribucion_b ) )

# Construir intervalos de confianza .
intervalo_norm <- boot.ci ( distribucion_b , conf = 1 - alfa , type = " norm " )
cat ( " \n\nIntervalo de confianza usando distribuci ó n Z :\n " )
print ( intervalo_norm )

intervalo_perc <- boot.ci ( distribucion_b , conf = 1 - alfa , type = " perc " )

cat ( "\n\nIntervalo de confianza usando percentiles :\n " )
print ( intervalo_perc )

intervalo_bca <- boot.ci ( distribucion_b , conf = 1 - alfa , type = " bca " )
cat ( "\n\nIntervalo de de confianza BCa :\ n ")

print ( intervalo_bca )
# Construir distribuci ó n bootstrap usando el paquete bootES .
set.seed (432)

distribucion_bootstrapES <- bootES ( muestra , R = B , ci.type = " bca " ,
ci.conf = 1 - alfa , plot = TRUE )

print ( distribucion_bootstrapES )
```

