---
title: "Wald_2_prop"
output: html_document
date: "2024-05-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
n_hombres <- 48
n_mujeres <- 42
exito_hombres <-26
exito_mujeres <-20
alfa <- 0.05
valor_nulo <- 0

#probabilidad de exito
p_hombres <- exito_hombres/n_hombres
p_mujeres <- exito_mujeres/n_mujeres

diferencia <- p_hombres - p_mujeres

#construccion de intervalo de confinza, si es dado en enunciado esta prate no es necesaria
error_hombres <- (p_hombres * (1- p_hombres)) / n_hombres
error_mujeres <- (p_mujeres * (1- p_mujeres)) / n_mujeres

error_est <- sqrt(error_hombres + error_mujeres)
Z_critico <- qnorm(alfa/2, lower.tail = FALSE)
inferior <- diferencia - Z_critico*error_est
superior <- diferencia + Z_critico*error_est

#hipotesis
P_agrupada <- (exito_hombres + exito_mujeres)/(n_hombres+ n_mujeres)
error_hombres2 <- (P_agrupada * (1 - P_agrupada)) /n_hombres
error_mujeres2 <- (P_agrupada * (1- P_agrupada)) /n_mujeres
error_est_hip <- sqrt(error_hombres2 + error_mujeres2)
Z <- (diferencia - valor_nulo)/error_est_hip
p <- 2 * pnorm(Z, lower.tail = FALSE)
```

