---
title: "Zunamuestra"
author: "GonzaloArevalo, Ivan Misle"
date: "2024-05-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(TeachingDemos)
library(ggpubr)

muestra <- c(19, 20, 21, 27, 30, 29, 22, 28, 25, 24, 29, 27, 23, 20, 22,
             24, 25, 26, 22, 23, 21, 25, 29, 27, 27, 24, 25, 22, 21, 31)

desv_est <- 2.32
n <- length(muestra)
valor_nulo <- 20

datos <- data.frame(muestra)

normalidad <- shapiro.test(muestra)
print(normalidad)

alfa <- 0.01
media <- mean(muestra)

#calcular estadistico de prueba
Z <- (media-valor_nulo) / (desv_est / sqrt(n))

#calcular el valor de p
p <- 2* pnorm(Z, lower.tail = FALSE)

#Hacer prueba Z
prueba1 <- z.test(muestra, mu = valor_nulo, n = 20, alternative = "two.sided", 
                  stdev = desv_est,conf.level = 1 - alfa)
print(prueba1)

#otra opscion usando la muestra directamente
prueba2 <- z.test(muestra, mu = valor_nulo, alternative = "two.sided", 
                  stdev = desv_est,conf.level = 1 - alfa)
print(prueba2)
```

