library ( tidyverse )
library ( ggpubr )
 library ( ez )

# Crear el data frame en formato ancho .
A <- c (23 , 19 , 25 , 23 , 20)
B <- c (26 , 24 , 28 , 23 , 29)
C <- c (19 , 24 , 20 , 21 , 17)
datos <- data . frame (A , B , C )
# Llevar data frame a formato largo .
datos <- datos %> % pivot _ longer ( c ( " A " , " B " , " C " ) ,
names _ to = " algoritmo " ,values _ to = " tiempo " )

datos [[ " algoritmo " ]] <- factor ( datos [[ " algoritmo " ]])
datos [[ " instancia " ]] <- factor (1: nrow ( datos ) )

# Comprobci 칩 n de normalidad .
g <- ggqqplot ( datos ,x = " tiempo " ,y = " algoritmo " ,color = " algoritmo " )
# Pr ocedi miento ANOVA con aov () .
cat ( " Pro ce dimi ent o ANOVA usando aov \ n \ n " )
prueba <- aov ( tiempo ~ algoritmo , data = datos )
print ( summary ( prueba ) )
# Pr ocedi miento ANOVA con ezANOVA () .
cat ( " \ n \ nPro ced imie nto ANOVA usando ezANOVA \ n \ n " )
prueba2 <- ezANOVA (data = datos ,dv = tiempo ,between = algoritmo ,wid = instancia ,return _ aov = TRUE )
print ( prueba2 )
# Gr 치 fico del tama 침 o del efecto .
g2 <- ezPlot (
data = datos ,
dv = tiempo ,
wid = instancia ,
between = algoritmo ,y _ lab = " Tiempo promedio de ejecuci 칩 n [ ms ] " ,
x = algoritmo ) g2 <- g2 + theme _ pubr ()

print ( g2)